version: '3.7'
services:
  keeper:
    container_name: Keeper
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - type: bind
        source: ./config/config.json
        target: /config/config.json
    restart: always
    env_file:
      - .env

volumes:
  app:
